name: Build and Upload JAR

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Grant execute permissions for Gradle wrapper
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      # Step 4: Build the JAR file
      - name: Build JAR
        run: ./gradlew build

      # Step 5: Upload the built JAR as an artifact
      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: addictive-experience-jar
          path: build/libs/*.jar
