name: Build and Upload Final JAR

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true # Initialize submodules automatically

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Grant execute permission for Gradle wrapper
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      # Step 4: Build the shadow JAR
      - name: Build shadow JAR
        run: ./gradlew :core:shadowJar

      # Step 5: Upload the final JAR as an artifact
      - name: Upload final JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: addictive-experience-final-jar
          path: core/build/libs/addictive-experience.jar
